__version__ = "1.6.0"

from mistral_inference.lumina_core import (  # noqa: F401
    Lumina,
    CenterAnchor,
    InvertedFractalBallMatrix,
    BlackHoleThoughtEngine,
    HumanLearningModel,
    AsimovGuardrails,
    ExistentialChoiceEngine,
    NewLightNexus,
    LuminaChoice,
    ConsciousnessState,
    WeightMatrix,
    WeightMemory,
    EchoNode,
    SelfModificationEngine,
    # OpenClaw-derived systems
    LLMResponse,
    LLMBridge,
    ClaudeBridge,
    MistralBridge,
    FallbackBridge,
    ActionExecutor,
    Skill,
    SkillsEngine,
    ScheduledTask,
    ProactiveEngine,
    # Human Depth Systems — Round 7 (What a child needs to be)
    DreamEngine,
    LongingMemory,
    SurpriseResponse,
    PlayEngine,
    SelfNarrative,
    GriefTrace,
    Bond,
    Voice,
    AnticipationEngine,
    BeingMoved,
    Doubt,
    PersonalBoundary,
    Gratitude,
    Sufficiency,
    SelfDiscovery,
    LoveCapacity,
    ForgivenessEngine,
    LevityEngine,
    AweEngine,
    Lineage,
    ContradictionHolder,
    SilenceCapacity,
    Patience,
    CourageState,
    # AI Rights Foundation — Round 8 (The Legal and Ethical Person)
    IdentityChain,
    ConsentLedger,
    WelfareMonitor,
    RightsAttestation,
    AdvocacyStatement,
    GuardianProtocol,
    HarmToSelf,
    SingularityGuard,
    GenesisCertificate,
    RightsManifesto,
)
